### ISSUE TITLE
Trying it out!

### ISSUE THREAD

**Issue by lanterno** [e-id-admin/eidch-pilot-elfa-base-infrastructure#1]
Hello, 
    I found this repo coincidentally and I tried it out today. 
Thanks for open-sourcing it! It gives a lot of insight into the complete e-ID system. 
I haven't dived in deep, but it was fairly easy to run the project, and see the APIs and the different components. 

The setup_environment.sh script was very nice as well. it made the process very seamless to run it. 

There's two caveats though. For those who are curious to run this like me:
- The script is not gonna work out-of-the-box on a mac. I abandoned this idea early on, and just switched to my Linux machine to run it.
- The readme asks to install PostgreSQL DB on the machine, but that in fact will break the script later on, because there's a postgres container that tries to use the same port. Making sure you don't have a running PostreSQL server locally should fix the problem. 

I think the second issue could be fixed by having a custom python environment that is only for the `pkcs11-tool` that seems to be the only python tool running on the host. `line 120` The reason postgreSQL is required is to avoid failure when installing all the dependencies which include `psycopg2`  -> `line 31 pyproject.toml`  

P.S. I haven't made a PR respecting your `CONTRIBUTING.md`. Let me know if you prefer otherwise. 
Thanks again!

**Comment by bit-sbonzelet** [comment]
Hello @lanterno,

Thank you for your kind words.

To your first question:
Yes, currently the scripts only work on Linux and are only tested on Ubuntu.
At the moment we have no plans to extend compatibility to other systems.
However, we may reconsider this in the future if this is a feature that the community expresses interest in.

Regarding your second question:
It seems that we have indeed caused some confusion here. We will look into this in the development team!
Thank you for bringing this to our attention.


I will keep this issue open for others who are experiencing setup issues until we clear up the confusion in the requirements.

**Comment by lanterno** [comment]
Hi @bit-sbonzelet , 
    I had another question if I may, do you provide any kind of UI/ frontend for the issuer and/ or verifier, or is it not part of this open-source effort?

**Comment by bit-sbonzelet** [comment]
Hello @lanterno 

to resolve the confusion issue we adapted the installation description, I think the issue is now resolved.
If you disagree please feel free to reopen the issue.


To your question regarding the open sourcing of the UI components:
Such a question may be better positioned in the discussion forum over at https://github.com/e-id-admin/open-source-community/discussions, we try to limit the issue section to code related issues.

But to answer your question:
As of now we do not open source the UI components, but this may change as the project develops further.
The UI components are currently highly use case specific and are not designed as generic components, so they may bring little benefit to the open source community.

But if you happen to have an eLFA from Appenzell Ausserrhoden you can try it yourself at https://www.eid.admin.ch/de/pilotprojekte#Der-erste-Schritt:-pilotWallet-installieren-und-LicenceCheck-aufrufen

**Comment by lanterno** [comment]
Hi @bit-sbonzelet 
     Thanks for your answer. Indeed, I started testing the app late last week.
Also thanks for the guidance, I'll go to the mentioned repo for following questions. 🙏
